{% set name = "xcube-clms" %}
{% set version = "1.3.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xcube-dev/xcube-clms/archive/v{{ version }}.tar.gz
  sha256: 97fc1569fc745562cdaae88e0abda3ba42ac20ed00a9d87d27e2b405d3700fa8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2.0
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - xarray
    - xcube >=1.9.0
    - ipywidgets
    - cryptography
    - fsspec
    - zappend
    - h5netcdf
    - boto3 ==1.37.3
    - libgdal-netcdf
    - python-dotenv

test:
  imports:
    - xcube_clms
  requires:
    - python {{ python_min }}

about:
  summary: xcube datastore for accessing datasets through the CLMS API
  home: https://github.com/xcube-dev/xcube-clms/
  license: MIT
  license_file: LICENSE
  description: The xcube-clms Python package provides an xcube data store that enables access to datasets hosted by the Copernicus Land Monitoring Service (CLMS). The data store is called "clms" and implemented as an xcube plugin. It uses the CLMS API under the hood.
  dev_url: https://github.com/xcube-dev/xcube-clms/

extra:
  recipe-maintainers:
    - AliceBalfanz
    - pont-us
    - b-yogesh
    - clarasb
    - forman
    - konstntokas
    - TejasMorbagal
    - thomasstorm
    - TonioF
