{% set name = "xcube-clms" %}
{% set version = "1.0.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xcube-dev/xcube-clms/archive/v{{ version }}.tar.gz
  sha256: 1a092a9b8021bc9ea6354125328854402e8c1277267b7048b8c6c409f6e8c667

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2.0
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - xarray
    - xcube >=1.8.1
    - ipywidgets
    - cryptography
    - fsspec

test:
  imports:
    - xcube_clms
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: xcube datastore for accessing datasets through the CLMS API
  home: https://github.com/xcube-dev/xcube-clms/
  license: MIT
  license_file: LICENSE
  description: The xcube-clms Python package provides an xcube data store that enables access to datasets hosted by the Copernicus Land Monitoring Service (CLMS). The data store is called "clms" and implemented as an xcube plugin. It uses the CLMS API under the hood.
  dev_url: https://github.com/xcube-dev/xcube-clms/

extra:
  recipe-maintainers:
    - b-yogesh
    - konstntokas
    - forman
    - pont-us
    - AliceBalfanz
    - TonioF
